//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Users\colin\Documents\GitHub\AS2017B\AS2017B\src\AS.GraphQL\GraphQL.g4 by ANTLR 4.6

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;

namespace GraphQL
{
    /// <summary>
    /// This interface defines a complete listener for a parse tree produced by
    /// <see cref="GraphQLParser"/>.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6")]
    public interface IGraphQLListener : IParseTreeListener {
        /// <summary>
        /// Enter a parse tree produced by <see cref="GraphQLParser.document"/>.
        /// </summary>
        /// <param name="context">The parse tree.</param>
        void EnterDocument([NotNull] GraphQLParser.DocumentContext context);
        /// <summary>
        /// Exit a parse tree produced by <see cref="GraphQLParser.document"/>.
        /// </summary>
        /// <param name="context">The parse tree.</param>
        void ExitDocument([NotNull] GraphQLParser.DocumentContext context);
        /// <summary>
        /// Enter a parse tree produced by <see cref="GraphQLParser.definition"/>.
        /// </summary>
        /// <param name="context">The parse tree.</param>
        void EnterDefinition([NotNull] GraphQLParser.DefinitionContext context);
        /// <summary>
        /// Exit a parse tree produced by <see cref="GraphQLParser.definition"/>.
        /// </summary>
        /// <param name="context">The parse tree.</param>
        void ExitDefinition([NotNull] GraphQLParser.DefinitionContext context);
        /// <summary>
        /// Enter a parse tree produced by <see cref="GraphQLParser.operationDefinition"/>.
        /// </summary>
        /// <param name="context">The parse tree.</param>
        void EnterOperationDefinition([NotNull] GraphQLParser.OperationDefinitionContext context);
        /// <summary>
        /// Exit a parse tree produced by <see cref="GraphQLParser.operationDefinition"/>.
        /// </summary>
        /// <param name="context">The parse tree.</param>
        void ExitOperationDefinition([NotNull] GraphQLParser.OperationDefinitionContext context);
        /// <summary>
        /// Enter a parse tree produced by <see cref="GraphQLParser.selectionSet"/>.
        /// </summary>
        /// <param name="context">The parse tree.</param>
        void EnterSelectionSet([NotNull] GraphQLParser.SelectionSetContext context);
        /// <summary>
        /// Exit a parse tree produced by <see cref="GraphQLParser.selectionSet"/>.
        /// </summary>
        /// <param name="context">The parse tree.</param>
        void ExitSelectionSet([NotNull] GraphQLParser.SelectionSetContext context);
        /// <summary>
        /// Enter a parse tree produced by <see cref="GraphQLParser.operationType"/>.
        /// </summary>
        /// <param name="context">The parse tree.</param>
        void EnterOperationType([NotNull] GraphQLParser.OperationTypeContext context);
        /// <summary>
        /// Exit a parse tree produced by <see cref="GraphQLParser.operationType"/>.
        /// </summary>
        /// <param name="context">The parse tree.</param>
        void ExitOperationType([NotNull] GraphQLParser.OperationTypeContext context);
        /// <summary>
        /// Enter a parse tree produced by <see cref="GraphQLParser.selection"/>.
        /// </summary>
        /// <param name="context">The parse tree.</param>
        void EnterSelection([NotNull] GraphQLParser.SelectionContext context);
        /// <summary>
        /// Exit a parse tree produced by <see cref="GraphQLParser.selection"/>.
        /// </summary>
        /// <param name="context">The parse tree.</param>
        void ExitSelection([NotNull] GraphQLParser.SelectionContext context);
        /// <summary>
        /// Enter a parse tree produced by <see cref="GraphQLParser.field"/>.
        /// </summary>
        /// <param name="context">The parse tree.</param>
        void EnterField([NotNull] GraphQLParser.FieldContext context);
        /// <summary>
        /// Exit a parse tree produced by <see cref="GraphQLParser.field"/>.
        /// </summary>
        /// <param name="context">The parse tree.</param>
        void ExitField([NotNull] GraphQLParser.FieldContext context);
        /// <summary>
        /// Enter a parse tree produced by <see cref="GraphQLParser.fieldName"/>.
        /// </summary>
        /// <param name="context">The parse tree.</param>
        void EnterFieldName([NotNull] GraphQLParser.FieldNameContext context);
        /// <summary>
        /// Exit a parse tree produced by <see cref="GraphQLParser.fieldName"/>.
        /// </summary>
        /// <param name="context">The parse tree.</param>
        void ExitFieldName([NotNull] GraphQLParser.FieldNameContext context);
        /// <summary>
        /// Enter a parse tree produced by <see cref="GraphQLParser.alias"/>.
        /// </summary>
        /// <param name="context">The parse tree.</param>
        void EnterAlias([NotNull] GraphQLParser.AliasContext context);
        /// <summary>
        /// Exit a parse tree produced by <see cref="GraphQLParser.alias"/>.
        /// </summary>
        /// <param name="context">The parse tree.</param>
        void ExitAlias([NotNull] GraphQLParser.AliasContext context);
        /// <summary>
        /// Enter a parse tree produced by <see cref="GraphQLParser.arguments"/>.
        /// </summary>
        /// <param name="context">The parse tree.</param>
        void EnterArguments([NotNull] GraphQLParser.ArgumentsContext context);
        /// <summary>
        /// Exit a parse tree produced by <see cref="GraphQLParser.arguments"/>.
        /// </summary>
        /// <param name="context">The parse tree.</param>
        void ExitArguments([NotNull] GraphQLParser.ArgumentsContext context);
        /// <summary>
        /// Enter a parse tree produced by <see cref="GraphQLParser.argument"/>.
        /// </summary>
        /// <param name="context">The parse tree.</param>
        void EnterArgument([NotNull] GraphQLParser.ArgumentContext context);
        /// <summary>
        /// Exit a parse tree produced by <see cref="GraphQLParser.argument"/>.
        /// </summary>
        /// <param name="context">The parse tree.</param>
        void ExitArgument([NotNull] GraphQLParser.ArgumentContext context);
        /// <summary>
        /// Enter a parse tree produced by <see cref="GraphQLParser.fragmentSpread"/>.
        /// </summary>
        /// <param name="context">The parse tree.</param>
        void EnterFragmentSpread([NotNull] GraphQLParser.FragmentSpreadContext context);
        /// <summary>
        /// Exit a parse tree produced by <see cref="GraphQLParser.fragmentSpread"/>.
        /// </summary>
        /// <param name="context">The parse tree.</param>
        void ExitFragmentSpread([NotNull] GraphQLParser.FragmentSpreadContext context);
        /// <summary>
        /// Enter a parse tree produced by <see cref="GraphQLParser.inlineFragment"/>.
        /// </summary>
        /// <param name="context">The parse tree.</param>
        void EnterInlineFragment([NotNull] GraphQLParser.InlineFragmentContext context);
        /// <summary>
        /// Exit a parse tree produced by <see cref="GraphQLParser.inlineFragment"/>.
        /// </summary>
        /// <param name="context">The parse tree.</param>
        void ExitInlineFragment([NotNull] GraphQLParser.InlineFragmentContext context);
        /// <summary>
        /// Enter a parse tree produced by <see cref="GraphQLParser.fragmentDefinition"/>.
        /// </summary>
        /// <param name="context">The parse tree.</param>
        void EnterFragmentDefinition([NotNull] GraphQLParser.FragmentDefinitionContext context);
        /// <summary>
        /// Exit a parse tree produced by <see cref="GraphQLParser.fragmentDefinition"/>.
        /// </summary>
        /// <param name="context">The parse tree.</param>
        void ExitFragmentDefinition([NotNull] GraphQLParser.FragmentDefinitionContext context);
        /// <summary>
        /// Enter a parse tree produced by <see cref="GraphQLParser.fragmentName"/>.
        /// </summary>
        /// <param name="context">The parse tree.</param>
        void EnterFragmentName([NotNull] GraphQLParser.FragmentNameContext context);
        /// <summary>
        /// Exit a parse tree produced by <see cref="GraphQLParser.fragmentName"/>.
        /// </summary>
        /// <param name="context">The parse tree.</param>
        void ExitFragmentName([NotNull] GraphQLParser.FragmentNameContext context);
        /// <summary>
        /// Enter a parse tree produced by <see cref="GraphQLParser.directives"/>.
        /// </summary>
        /// <param name="context">The parse tree.</param>
        void EnterDirectives([NotNull] GraphQLParser.DirectivesContext context);
        /// <summary>
        /// Exit a parse tree produced by <see cref="GraphQLParser.directives"/>.
        /// </summary>
        /// <param name="context">The parse tree.</param>
        void ExitDirectives([NotNull] GraphQLParser.DirectivesContext context);
        /// <summary>
        /// Enter a parse tree produced by <see cref="GraphQLParser.directive"/>.
        /// </summary>
        /// <param name="context">The parse tree.</param>
        void EnterDirective([NotNull] GraphQLParser.DirectiveContext context);
        /// <summary>
        /// Exit a parse tree produced by <see cref="GraphQLParser.directive"/>.
        /// </summary>
        /// <param name="context">The parse tree.</param>
        void ExitDirective([NotNull] GraphQLParser.DirectiveContext context);
        /// <summary>
        /// Enter a parse tree produced by <see cref="GraphQLParser.typeCondition"/>.
        /// </summary>
        /// <param name="context">The parse tree.</param>
        void EnterTypeCondition([NotNull] GraphQLParser.TypeConditionContext context);
        /// <summary>
        /// Exit a parse tree produced by <see cref="GraphQLParser.typeCondition"/>.
        /// </summary>
        /// <param name="context">The parse tree.</param>
        void ExitTypeCondition([NotNull] GraphQLParser.TypeConditionContext context);
        /// <summary>
        /// Enter a parse tree produced by <see cref="GraphQLParser.variableDefinitions"/>.
        /// </summary>
        /// <param name="context">The parse tree.</param>
        void EnterVariableDefinitions([NotNull] GraphQLParser.VariableDefinitionsContext context);
        /// <summary>
        /// Exit a parse tree produced by <see cref="GraphQLParser.variableDefinitions"/>.
        /// </summary>
        /// <param name="context">The parse tree.</param>
        void ExitVariableDefinitions([NotNull] GraphQLParser.VariableDefinitionsContext context);
        /// <summary>
        /// Enter a parse tree produced by <see cref="GraphQLParser.variableDefinition"/>.
        /// </summary>
        /// <param name="context">The parse tree.</param>
        void EnterVariableDefinition([NotNull] GraphQLParser.VariableDefinitionContext context);
        /// <summary>
        /// Exit a parse tree produced by <see cref="GraphQLParser.variableDefinition"/>.
        /// </summary>
        /// <param name="context">The parse tree.</param>
        void ExitVariableDefinition([NotNull] GraphQLParser.VariableDefinitionContext context);
        /// <summary>
        /// Enter a parse tree produced by <see cref="GraphQLParser.variable"/>.
        /// </summary>
        /// <param name="context">The parse tree.</param>
        void EnterVariable([NotNull] GraphQLParser.VariableContext context);
        /// <summary>
        /// Exit a parse tree produced by <see cref="GraphQLParser.variable"/>.
        /// </summary>
        /// <param name="context">The parse tree.</param>
        void ExitVariable([NotNull] GraphQLParser.VariableContext context);
        /// <summary>
        /// Enter a parse tree produced by <see cref="GraphQLParser.defaultValue"/>.
        /// </summary>
        /// <param name="context">The parse tree.</param>
        void EnterDefaultValue([NotNull] GraphQLParser.DefaultValueContext context);
        /// <summary>
        /// Exit a parse tree produced by <see cref="GraphQLParser.defaultValue"/>.
        /// </summary>
        /// <param name="context">The parse tree.</param>
        void ExitDefaultValue([NotNull] GraphQLParser.DefaultValueContext context);
        /// <summary>
        /// Enter a parse tree produced by <see cref="GraphQLParser.valueOrVariable"/>.
        /// </summary>
        /// <param name="context">The parse tree.</param>
        void EnterValueOrVariable([NotNull] GraphQLParser.ValueOrVariableContext context);
        /// <summary>
        /// Exit a parse tree produced by <see cref="GraphQLParser.valueOrVariable"/>.
        /// </summary>
        /// <param name="context">The parse tree.</param>
        void ExitValueOrVariable([NotNull] GraphQLParser.ValueOrVariableContext context);
        /// <summary>
        /// Enter a parse tree produced by the <c>stringValue</c>
        /// labeled alternative in <see cref="GraphQLParser.value"/>.
        /// </summary>
        /// <param name="context">The parse tree.</param>
        void EnterStringValue([NotNull] GraphQLParser.StringValueContext context);
        /// <summary>
        /// Exit a parse tree produced by the <c>stringValue</c>
        /// labeled alternative in <see cref="GraphQLParser.value"/>.
        /// </summary>
        /// <param name="context">The parse tree.</param>
        void ExitStringValue([NotNull] GraphQLParser.StringValueContext context);
        /// <summary>
        /// Enter a parse tree produced by the <c>numberValue</c>
        /// labeled alternative in <see cref="GraphQLParser.value"/>.
        /// </summary>
        /// <param name="context">The parse tree.</param>
        void EnterNumberValue([NotNull] GraphQLParser.NumberValueContext context);
        /// <summary>
        /// Exit a parse tree produced by the <c>numberValue</c>
        /// labeled alternative in <see cref="GraphQLParser.value"/>.
        /// </summary>
        /// <param name="context">The parse tree.</param>
        void ExitNumberValue([NotNull] GraphQLParser.NumberValueContext context);
        /// <summary>
        /// Enter a parse tree produced by the <c>booleanValue</c>
        /// labeled alternative in <see cref="GraphQLParser.value"/>.
        /// </summary>
        /// <param name="context">The parse tree.</param>
        void EnterBooleanValue([NotNull] GraphQLParser.BooleanValueContext context);
        /// <summary>
        /// Exit a parse tree produced by the <c>booleanValue</c>
        /// labeled alternative in <see cref="GraphQLParser.value"/>.
        /// </summary>
        /// <param name="context">The parse tree.</param>
        void ExitBooleanValue([NotNull] GraphQLParser.BooleanValueContext context);
        /// <summary>
        /// Enter a parse tree produced by the <c>arrayValue</c>
        /// labeled alternative in <see cref="GraphQLParser.value"/>.
        /// </summary>
        /// <param name="context">The parse tree.</param>
        void EnterArrayValue([NotNull] GraphQLParser.ArrayValueContext context);
        /// <summary>
        /// Exit a parse tree produced by the <c>arrayValue</c>
        /// labeled alternative in <see cref="GraphQLParser.value"/>.
        /// </summary>
        /// <param name="context">The parse tree.</param>
        void ExitArrayValue([NotNull] GraphQLParser.ArrayValueContext context);
        /// <summary>
        /// Enter a parse tree produced by the <c>objectValue</c>
        /// labeled alternative in <see cref="GraphQLParser.value"/>.
        /// </summary>
        /// <param name="context">The parse tree.</param>
        void EnterObjectValue([NotNull] GraphQLParser.ObjectValueContext context);
        /// <summary>
        /// Exit a parse tree produced by the <c>objectValue</c>
        /// labeled alternative in <see cref="GraphQLParser.value"/>.
        /// </summary>
        /// <param name="context">The parse tree.</param>
        void ExitObjectValue([NotNull] GraphQLParser.ObjectValueContext context);
        /// <summary>
        /// Enter a parse tree produced by the <c>enumValue</c>
        /// labeled alternative in <see cref="GraphQLParser.value"/>.
        /// </summary>
        /// <param name="context">The parse tree.</param>
        void EnterEnumValue([NotNull] GraphQLParser.EnumValueContext context);
        /// <summary>
        /// Exit a parse tree produced by the <c>enumValue</c>
        /// labeled alternative in <see cref="GraphQLParser.value"/>.
        /// </summary>
        /// <param name="context">The parse tree.</param>
        void ExitEnumValue([NotNull] GraphQLParser.EnumValueContext context);
        /// <summary>
        /// Enter a parse tree produced by <see cref="GraphQLParser.type"/>.
        /// </summary>
        /// <param name="context">The parse tree.</param>
        void EnterType([NotNull] GraphQLParser.TypeContext context);
        /// <summary>
        /// Exit a parse tree produced by <see cref="GraphQLParser.type"/>.
        /// </summary>
        /// <param name="context">The parse tree.</param>
        void ExitType([NotNull] GraphQLParser.TypeContext context);
        /// <summary>
        /// Enter a parse tree produced by <see cref="GraphQLParser.typeName"/>.
        /// </summary>
        /// <param name="context">The parse tree.</param>
        void EnterTypeName([NotNull] GraphQLParser.TypeNameContext context);
        /// <summary>
        /// Exit a parse tree produced by <see cref="GraphQLParser.typeName"/>.
        /// </summary>
        /// <param name="context">The parse tree.</param>
        void ExitTypeName([NotNull] GraphQLParser.TypeNameContext context);
        /// <summary>
        /// Enter a parse tree produced by <see cref="GraphQLParser.listType"/>.
        /// </summary>
        /// <param name="context">The parse tree.</param>
        void EnterListType([NotNull] GraphQLParser.ListTypeContext context);
        /// <summary>
        /// Exit a parse tree produced by <see cref="GraphQLParser.listType"/>.
        /// </summary>
        /// <param name="context">The parse tree.</param>
        void ExitListType([NotNull] GraphQLParser.ListTypeContext context);
        /// <summary>
        /// Enter a parse tree produced by <see cref="GraphQLParser.nonNullType"/>.
        /// </summary>
        /// <param name="context">The parse tree.</param>
        void EnterNonNullType([NotNull] GraphQLParser.NonNullTypeContext context);
        /// <summary>
        /// Exit a parse tree produced by <see cref="GraphQLParser.nonNullType"/>.
        /// </summary>
        /// <param name="context">The parse tree.</param>
        void ExitNonNullType([NotNull] GraphQLParser.NonNullTypeContext context);
        /// <summary>
        /// Enter a parse tree produced by <see cref="GraphQLParser.array"/>.
        /// </summary>
        /// <param name="context">The parse tree.</param>
        void EnterArray([NotNull] GraphQLParser.ArrayContext context);
        /// <summary>
        /// Exit a parse tree produced by <see cref="GraphQLParser.array"/>.
        /// </summary>
        /// <param name="context">The parse tree.</param>
        void ExitArray([NotNull] GraphQLParser.ArrayContext context);
        /// <summary>
        /// Enter a parse tree produced by <see cref="GraphQLParser.object"/>.
        /// </summary>
        /// <param name="context">The parse tree.</param>
        void EnterObject([NotNull] GraphQLParser.ObjectContext context);
        /// <summary>
        /// Exit a parse tree produced by <see cref="GraphQLParser.object"/>.
        /// </summary>
        /// <param name="context">The parse tree.</param>
        void ExitObject([NotNull] GraphQLParser.ObjectContext context);
    }
}
