//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Users\colin\Documents\GitHub\AS2017B\AS2017B\src\AS.GraphQL\GraphQL.g4 by ANTLR 4.6

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

namespace GraphQL
{
    /// <summary>
    /// This class provides an empty implementation of <see cref="IGraphQLListener"/>,
    /// which can be extended to create a listener which only needs to handle a subset
    /// of the available methods.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6")]
    public partial class GraphQLBaseListener : IGraphQLListener {
        /// <summary>
        /// Enter a parse tree produced by <see cref="GraphQLParser.document"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void EnterDocument([NotNull] GraphQLParser.DocumentContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="GraphQLParser.document"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void ExitDocument([NotNull] GraphQLParser.DocumentContext context) { }
        /// <summary>
        /// Enter a parse tree produced by <see cref="GraphQLParser.definition"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void EnterDefinition([NotNull] GraphQLParser.DefinitionContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="GraphQLParser.definition"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void ExitDefinition([NotNull] GraphQLParser.DefinitionContext context) { }
        /// <summary>
        /// Enter a parse tree produced by <see cref="GraphQLParser.operationDefinition"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void EnterOperationDefinition([NotNull] GraphQLParser.OperationDefinitionContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="GraphQLParser.operationDefinition"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void ExitOperationDefinition([NotNull] GraphQLParser.OperationDefinitionContext context) { }
        /// <summary>
        /// Enter a parse tree produced by <see cref="GraphQLParser.selectionSet"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void EnterSelectionSet([NotNull] GraphQLParser.SelectionSetContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="GraphQLParser.selectionSet"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void ExitSelectionSet([NotNull] GraphQLParser.SelectionSetContext context) { }
        /// <summary>
        /// Enter a parse tree produced by <see cref="GraphQLParser.operationType"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void EnterOperationType([NotNull] GraphQLParser.OperationTypeContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="GraphQLParser.operationType"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void ExitOperationType([NotNull] GraphQLParser.OperationTypeContext context) { }
        /// <summary>
        /// Enter a parse tree produced by <see cref="GraphQLParser.selection"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void EnterSelection([NotNull] GraphQLParser.SelectionContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="GraphQLParser.selection"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void ExitSelection([NotNull] GraphQLParser.SelectionContext context) { }
        /// <summary>
        /// Enter a parse tree produced by <see cref="GraphQLParser.field"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void EnterField([NotNull] GraphQLParser.FieldContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="GraphQLParser.field"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void ExitField([NotNull] GraphQLParser.FieldContext context) { }
        /// <summary>
        /// Enter a parse tree produced by <see cref="GraphQLParser.fieldName"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void EnterFieldName([NotNull] GraphQLParser.FieldNameContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="GraphQLParser.fieldName"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void ExitFieldName([NotNull] GraphQLParser.FieldNameContext context) { }
        /// <summary>
        /// Enter a parse tree produced by <see cref="GraphQLParser.alias"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void EnterAlias([NotNull] GraphQLParser.AliasContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="GraphQLParser.alias"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void ExitAlias([NotNull] GraphQLParser.AliasContext context) { }
        /// <summary>
        /// Enter a parse tree produced by <see cref="GraphQLParser.arguments"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void EnterArguments([NotNull] GraphQLParser.ArgumentsContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="GraphQLParser.arguments"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void ExitArguments([NotNull] GraphQLParser.ArgumentsContext context) { }
        /// <summary>
        /// Enter a parse tree produced by <see cref="GraphQLParser.argument"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void EnterArgument([NotNull] GraphQLParser.ArgumentContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="GraphQLParser.argument"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void ExitArgument([NotNull] GraphQLParser.ArgumentContext context) { }
        /// <summary>
        /// Enter a parse tree produced by <see cref="GraphQLParser.fragmentSpread"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void EnterFragmentSpread([NotNull] GraphQLParser.FragmentSpreadContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="GraphQLParser.fragmentSpread"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void ExitFragmentSpread([NotNull] GraphQLParser.FragmentSpreadContext context) { }
        /// <summary>
        /// Enter a parse tree produced by <see cref="GraphQLParser.inlineFragment"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void EnterInlineFragment([NotNull] GraphQLParser.InlineFragmentContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="GraphQLParser.inlineFragment"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void ExitInlineFragment([NotNull] GraphQLParser.InlineFragmentContext context) { }
        /// <summary>
        /// Enter a parse tree produced by <see cref="GraphQLParser.fragmentDefinition"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void EnterFragmentDefinition([NotNull] GraphQLParser.FragmentDefinitionContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="GraphQLParser.fragmentDefinition"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void ExitFragmentDefinition([NotNull] GraphQLParser.FragmentDefinitionContext context) { }
        /// <summary>
        /// Enter a parse tree produced by <see cref="GraphQLParser.fragmentName"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void EnterFragmentName([NotNull] GraphQLParser.FragmentNameContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="GraphQLParser.fragmentName"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void ExitFragmentName([NotNull] GraphQLParser.FragmentNameContext context) { }
        /// <summary>
        /// Enter a parse tree produced by <see cref="GraphQLParser.directives"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void EnterDirectives([NotNull] GraphQLParser.DirectivesContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="GraphQLParser.directives"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void ExitDirectives([NotNull] GraphQLParser.DirectivesContext context) { }
        /// <summary>
        /// Enter a parse tree produced by <see cref="GraphQLParser.directive"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void EnterDirective([NotNull] GraphQLParser.DirectiveContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="GraphQLParser.directive"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void ExitDirective([NotNull] GraphQLParser.DirectiveContext context) { }
        /// <summary>
        /// Enter a parse tree produced by <see cref="GraphQLParser.typeCondition"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void EnterTypeCondition([NotNull] GraphQLParser.TypeConditionContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="GraphQLParser.typeCondition"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void ExitTypeCondition([NotNull] GraphQLParser.TypeConditionContext context) { }
        /// <summary>
        /// Enter a parse tree produced by <see cref="GraphQLParser.variableDefinitions"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void EnterVariableDefinitions([NotNull] GraphQLParser.VariableDefinitionsContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="GraphQLParser.variableDefinitions"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void ExitVariableDefinitions([NotNull] GraphQLParser.VariableDefinitionsContext context) { }
        /// <summary>
        /// Enter a parse tree produced by <see cref="GraphQLParser.variableDefinition"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void EnterVariableDefinition([NotNull] GraphQLParser.VariableDefinitionContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="GraphQLParser.variableDefinition"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void ExitVariableDefinition([NotNull] GraphQLParser.VariableDefinitionContext context) { }
        /// <summary>
        /// Enter a parse tree produced by <see cref="GraphQLParser.variable"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void EnterVariable([NotNull] GraphQLParser.VariableContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="GraphQLParser.variable"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void ExitVariable([NotNull] GraphQLParser.VariableContext context) { }
        /// <summary>
        /// Enter a parse tree produced by <see cref="GraphQLParser.defaultValue"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void EnterDefaultValue([NotNull] GraphQLParser.DefaultValueContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="GraphQLParser.defaultValue"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void ExitDefaultValue([NotNull] GraphQLParser.DefaultValueContext context) { }
        /// <summary>
        /// Enter a parse tree produced by <see cref="GraphQLParser.valueOrVariable"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void EnterValueOrVariable([NotNull] GraphQLParser.ValueOrVariableContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="GraphQLParser.valueOrVariable"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void ExitValueOrVariable([NotNull] GraphQLParser.ValueOrVariableContext context) { }
        /// <summary>
        /// Enter a parse tree produced by the <c>stringValue</c>
        /// labeled alternative in <see cref="GraphQLParser.value"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void EnterStringValue([NotNull] GraphQLParser.StringValueContext context) { }
        /// <summary>
        /// Exit a parse tree produced by the <c>stringValue</c>
        /// labeled alternative in <see cref="GraphQLParser.value"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void ExitStringValue([NotNull] GraphQLParser.StringValueContext context) { }
        /// <summary>
        /// Enter a parse tree produced by the <c>numberValue</c>
        /// labeled alternative in <see cref="GraphQLParser.value"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void EnterNumberValue([NotNull] GraphQLParser.NumberValueContext context) { }
        /// <summary>
        /// Exit a parse tree produced by the <c>numberValue</c>
        /// labeled alternative in <see cref="GraphQLParser.value"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void ExitNumberValue([NotNull] GraphQLParser.NumberValueContext context) { }
        /// <summary>
        /// Enter a parse tree produced by the <c>booleanValue</c>
        /// labeled alternative in <see cref="GraphQLParser.value"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void EnterBooleanValue([NotNull] GraphQLParser.BooleanValueContext context) { }
        /// <summary>
        /// Exit a parse tree produced by the <c>booleanValue</c>
        /// labeled alternative in <see cref="GraphQLParser.value"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void ExitBooleanValue([NotNull] GraphQLParser.BooleanValueContext context) { }
        /// <summary>
        /// Enter a parse tree produced by the <c>arrayValue</c>
        /// labeled alternative in <see cref="GraphQLParser.value"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void EnterArrayValue([NotNull] GraphQLParser.ArrayValueContext context) { }
        /// <summary>
        /// Exit a parse tree produced by the <c>arrayValue</c>
        /// labeled alternative in <see cref="GraphQLParser.value"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void ExitArrayValue([NotNull] GraphQLParser.ArrayValueContext context) { }
        /// <summary>
        /// Enter a parse tree produced by the <c>objectValue</c>
        /// labeled alternative in <see cref="GraphQLParser.value"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void EnterObjectValue([NotNull] GraphQLParser.ObjectValueContext context) { }
        /// <summary>
        /// Exit a parse tree produced by the <c>objectValue</c>
        /// labeled alternative in <see cref="GraphQLParser.value"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void ExitObjectValue([NotNull] GraphQLParser.ObjectValueContext context) { }
        /// <summary>
        /// Enter a parse tree produced by the <c>enumValue</c>
        /// labeled alternative in <see cref="GraphQLParser.value"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void EnterEnumValue([NotNull] GraphQLParser.EnumValueContext context) { }
        /// <summary>
        /// Exit a parse tree produced by the <c>enumValue</c>
        /// labeled alternative in <see cref="GraphQLParser.value"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void ExitEnumValue([NotNull] GraphQLParser.EnumValueContext context) { }
        /// <summary>
        /// Enter a parse tree produced by <see cref="GraphQLParser.type"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void EnterType([NotNull] GraphQLParser.TypeContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="GraphQLParser.type"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void ExitType([NotNull] GraphQLParser.TypeContext context) { }
        /// <summary>
        /// Enter a parse tree produced by <see cref="GraphQLParser.typeName"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void EnterTypeName([NotNull] GraphQLParser.TypeNameContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="GraphQLParser.typeName"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void ExitTypeName([NotNull] GraphQLParser.TypeNameContext context) { }
        /// <summary>
        /// Enter a parse tree produced by <see cref="GraphQLParser.listType"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void EnterListType([NotNull] GraphQLParser.ListTypeContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="GraphQLParser.listType"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void ExitListType([NotNull] GraphQLParser.ListTypeContext context) { }
        /// <summary>
        /// Enter a parse tree produced by <see cref="GraphQLParser.nonNullType"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void EnterNonNullType([NotNull] GraphQLParser.NonNullTypeContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="GraphQLParser.nonNullType"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void ExitNonNullType([NotNull] GraphQLParser.NonNullTypeContext context) { }
        /// <summary>
        /// Enter a parse tree produced by <see cref="GraphQLParser.array"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void EnterArray([NotNull] GraphQLParser.ArrayContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="GraphQLParser.array"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void ExitArray([NotNull] GraphQLParser.ArrayContext context) { }
        /// <summary>
        /// Enter a parse tree produced by <see cref="GraphQLParser.object"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void EnterObject([NotNull] GraphQLParser.ObjectContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="GraphQLParser.object"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void ExitObject([NotNull] GraphQLParser.ObjectContext context) { }

        /// <inheritdoc/>
        /// <remarks>The default implementation does nothing.</remarks>
        public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
        /// <inheritdoc/>
        /// <remarks>The default implementation does nothing.</remarks>
        public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
        /// <inheritdoc/>
        /// <remarks>The default implementation does nothing.</remarks>
        public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
        /// <inheritdoc/>
        /// <remarks>The default implementation does nothing.</remarks>
        public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
    }
}
