// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AppForAnswers.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from AppForAnswers.proto</summary>
public static partial class AppForAnswersReflection {

  #region Descriptor
  /// <summary>File descriptor for AppForAnswers.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static AppForAnswersReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChNBcHBGb3JBbnN3ZXJzLnByb3RvIpYBCgxBNEFSZWxhdGlvbnMSIAoIRnJv",
          "bVR5cGUYASABKA4yDi5BNEFFbnRpdHlUeXBlEg4KBkZyb21JZBgCIAEoCRIe",
          "CgZUb1R5cGUYAyABKA4yDi5BNEFFbnRpdHlUeXBlEgwKBFRvSWQYBCABKAkS",
          "JgoMUmVsYXRpb25UeXBlGAUgASgOMhAuQTRBUmVsYXRpb25UeXBlIsMCCghB",
          "NEFQYXJ0eRIKCgJJZBgBIAEoCRIRCglGaXJzdE5hbWUYAiABKAkSEAoITGFz",
          "dE5hbWUYAyABKAkSEAoIVXNlck5hbWUYBCABKAkSEgoKQWxpYXNFbWFpbBgF",
          "IAEoCRIRCglSZWFsRW1haWwYBiABKAkSDgoGTW9iaWxlGAcgASgJEiAKCVBh",
          "cnR5VHlwZRgIIAEoDjINLkE0QVBhcnR5VHlwZRIpCg9SdW50aW1lUmVsYXRp",
          "b24YMiABKA4yEC5BNEFSZWxhdGlvblR5cGUSIQoOUmVsYXRlZFBhcnRpZXMY",
          "ZCADKAsyCS5BNEFQYXJ0eRInChFSZWxhdGVkQ2F0ZWdvcmllcxhlIAMoCzIM",
          "LkE0QUNhdGVnb3J5EiQKD1JlbGF0ZWRNZXNzYWdlcxhmIAMoCzILLkE0QU1l",
          "c3NhZ2UizAEKC0E0QUNhdGVnb3J5EgoKAklkGAEgASgJEhQKDENhdGVnb3J5",
          "TmFtZRgCIAEoCRIpCg9SdW50aW1lUmVsYXRpb24YMiABKA4yEC5BNEFSZWxh",
          "dGlvblR5cGUSJwoRUmVsYXRlZENhdGVnb3JpZXMYAyADKAsyDC5BNEFDYXRl",
          "Z29yeRIhCg5SZWxhdGVkUGFydGllcxgEIAMoCzIJLkE0QVBhcnR5EiQKD1Jl",
          "bGF0ZWRNZXNzYWdlcxhmIAMoCzILLkE0QU1lc3NhZ2Ui7AEKCkE0QU1lc3Nh",
          "Z2USCgoCSWQYASABKAkSDwoHQ29udGVudBgCIAEoCRIkCgtDb250ZW50VHlw",
          "ZRgDIAEoDjIPLkE0QUNvbnRlbnRUeXBlEikKD1J1bnRpbWVSZWxhdGlvbhgy",
          "IAEoDjIQLkE0QVJlbGF0aW9uVHlwZRIhCg5SZWxhdGVkUGFydGllcxhkIAMo",
          "CzIJLkE0QVBhcnR5EicKEVJlbGF0ZWRDYXRlZ29yaWVzGGUgAygLMgwuQTRB",
          "Q2F0ZWdvcnkSJAoPUmVsYXRlZE1lc3NhZ2VzGGYgAygLMgsuQTRBTWVzc2Fn",
          "ZSo1Cg1BNEFFbnRpdHlUeXBlEgkKBVBhcnR5EAASCwoHTWVzc2FnZRABEgwK",
          "CENhdGVnb3J5EAIqXwoPQTRBUmVsYXRpb25UeXBlEg8KC1BhcmVudENoaWxk",
          "EAASEgoOUmVsYXRlZE1lc3NhZ2UQARIUChBFeHBlcnRPbkNhdGVnb3J5EAIS",
          "EQoNQXV0aG9yTWVzc2FnZRADKhsKDkE0QUNvbnRlbnRUeXBlEgkKBUVtYWls",
          "EAAqMwoMQTRBUGFydHlUeXBlEgsKB0NvbXBhbnkQABIKCgZQZXJzb24QARIK",
          "CgZFeHBlcnQQAmIGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::A4AEntityType), typeof(global::A4ARelationType), typeof(global::A4AContentType), typeof(global::A4APartyType), }, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::A4ARelations), global::A4ARelations.Parser, new[]{ "FromType", "FromId", "ToType", "ToId", "RelationType" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::A4AParty), global::A4AParty.Parser, new[]{ "Id", "FirstName", "LastName", "UserName", "AliasEmail", "RealEmail", "Mobile", "PartyType", "RuntimeRelation", "RelatedParties", "RelatedCategories", "RelatedMessages" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::A4ACategory), global::A4ACategory.Parser, new[]{ "Id", "CategoryName", "RuntimeRelation", "RelatedCategories", "RelatedParties", "RelatedMessages" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::A4AMessage), global::A4AMessage.Parser, new[]{ "Id", "Content", "ContentType", "RuntimeRelation", "RelatedParties", "RelatedCategories", "RelatedMessages" }, null, null, null)
        }));
  }
  #endregion

}
#region Enums
public enum A4AEntityType {
  [pbr::OriginalName("Party")] Party = 0,
  [pbr::OriginalName("Message")] Message = 1,
  [pbr::OriginalName("Category")] Category = 2,
}

public enum A4ARelationType {
  [pbr::OriginalName("ParentChild")] ParentChild = 0,
  [pbr::OriginalName("RelatedMessage")] RelatedMessage = 1,
  [pbr::OriginalName("ExpertOnCategory")] ExpertOnCategory = 2,
  [pbr::OriginalName("AuthorMessage")] AuthorMessage = 3,
}

public enum A4AContentType {
  [pbr::OriginalName("Email")] Email = 0,
}

public enum A4APartyType {
  [pbr::OriginalName("Company")] Company = 0,
  [pbr::OriginalName("Person")] Person = 1,
  [pbr::OriginalName("Expert")] Expert = 2,
}

#endregion

#region Messages
public sealed partial class A4ARelations : pb::IMessage<A4ARelations> {
  private static readonly pb::MessageParser<A4ARelations> _parser = new pb::MessageParser<A4ARelations>(() => new A4ARelations());
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<A4ARelations> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::AppForAnswersReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public A4ARelations() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public A4ARelations(A4ARelations other) : this() {
    fromType_ = other.fromType_;
    fromId_ = other.fromId_;
    toType_ = other.toType_;
    toId_ = other.toId_;
    relationType_ = other.relationType_;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public A4ARelations Clone() {
    return new A4ARelations(this);
  }

  /// <summary>Field number for the "FromType" field.</summary>
  public const int FromTypeFieldNumber = 1;
  private global::A4AEntityType fromType_ = 0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::A4AEntityType FromType {
    get { return fromType_; }
    set {
      fromType_ = value;
    }
  }

  /// <summary>Field number for the "FromId" field.</summary>
  public const int FromIdFieldNumber = 2;
  private string fromId_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string FromId {
    get { return fromId_; }
    set {
      fromId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "ToType" field.</summary>
  public const int ToTypeFieldNumber = 3;
  private global::A4AEntityType toType_ = 0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::A4AEntityType ToType {
    get { return toType_; }
    set {
      toType_ = value;
    }
  }

  /// <summary>Field number for the "ToId" field.</summary>
  public const int ToIdFieldNumber = 4;
  private string toId_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string ToId {
    get { return toId_; }
    set {
      toId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "RelationType" field.</summary>
  public const int RelationTypeFieldNumber = 5;
  private global::A4ARelationType relationType_ = 0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::A4ARelationType RelationType {
    get { return relationType_; }
    set {
      relationType_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as A4ARelations);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(A4ARelations other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (FromType != other.FromType) return false;
    if (FromId != other.FromId) return false;
    if (ToType != other.ToType) return false;
    if (ToId != other.ToId) return false;
    if (RelationType != other.RelationType) return false;
    return true;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (FromType != 0) hash ^= FromType.GetHashCode();
    if (FromId.Length != 0) hash ^= FromId.GetHashCode();
    if (ToType != 0) hash ^= ToType.GetHashCode();
    if (ToId.Length != 0) hash ^= ToId.GetHashCode();
    if (RelationType != 0) hash ^= RelationType.GetHashCode();
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (FromType != 0) {
      output.WriteRawTag(8);
      output.WriteEnum((int) FromType);
    }
    if (FromId.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(FromId);
    }
    if (ToType != 0) {
      output.WriteRawTag(24);
      output.WriteEnum((int) ToType);
    }
    if (ToId.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(ToId);
    }
    if (RelationType != 0) {
      output.WriteRawTag(40);
      output.WriteEnum((int) RelationType);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (FromType != 0) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) FromType);
    }
    if (FromId.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(FromId);
    }
    if (ToType != 0) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ToType);
    }
    if (ToId.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(ToId);
    }
    if (RelationType != 0) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) RelationType);
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(A4ARelations other) {
    if (other == null) {
      return;
    }
    if (other.FromType != 0) {
      FromType = other.FromType;
    }
    if (other.FromId.Length != 0) {
      FromId = other.FromId;
    }
    if (other.ToType != 0) {
      ToType = other.ToType;
    }
    if (other.ToId.Length != 0) {
      ToId = other.ToId;
    }
    if (other.RelationType != 0) {
      RelationType = other.RelationType;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          input.SkipLastField();
          break;
        case 8: {
          fromType_ = (global::A4AEntityType) input.ReadEnum();
          break;
        }
        case 18: {
          FromId = input.ReadString();
          break;
        }
        case 24: {
          toType_ = (global::A4AEntityType) input.ReadEnum();
          break;
        }
        case 34: {
          ToId = input.ReadString();
          break;
        }
        case 40: {
          relationType_ = (global::A4ARelationType) input.ReadEnum();
          break;
        }
      }
    }
  }

}

public sealed partial class A4AParty : pb::IMessage<A4AParty> {
  private static readonly pb::MessageParser<A4AParty> _parser = new pb::MessageParser<A4AParty>(() => new A4AParty());
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<A4AParty> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::AppForAnswersReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public A4AParty() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public A4AParty(A4AParty other) : this() {
    id_ = other.id_;
    firstName_ = other.firstName_;
    lastName_ = other.lastName_;
    userName_ = other.userName_;
    aliasEmail_ = other.aliasEmail_;
    realEmail_ = other.realEmail_;
    mobile_ = other.mobile_;
    partyType_ = other.partyType_;
    runtimeRelation_ = other.runtimeRelation_;
    relatedParties_ = other.relatedParties_.Clone();
    relatedCategories_ = other.relatedCategories_.Clone();
    relatedMessages_ = other.relatedMessages_.Clone();
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public A4AParty Clone() {
    return new A4AParty(this);
  }

  /// <summary>Field number for the "Id" field.</summary>
  public const int IdFieldNumber = 1;
  private string id_ = "";
  /// <summary>
  /// this is the party identifier
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Id {
    get { return id_; }
    set {
      id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "FirstName" field.</summary>
  public const int FirstNameFieldNumber = 2;
  private string firstName_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string FirstName {
    get { return firstName_; }
    set {
      firstName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "LastName" field.</summary>
  public const int LastNameFieldNumber = 3;
  private string lastName_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string LastName {
    get { return lastName_; }
    set {
      lastName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "UserName" field.</summary>
  public const int UserNameFieldNumber = 4;
  private string userName_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string UserName {
    get { return userName_; }
    set {
      userName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "AliasEmail" field.</summary>
  public const int AliasEmailFieldNumber = 5;
  private string aliasEmail_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string AliasEmail {
    get { return aliasEmail_; }
    set {
      aliasEmail_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "RealEmail" field.</summary>
  public const int RealEmailFieldNumber = 6;
  private string realEmail_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string RealEmail {
    get { return realEmail_; }
    set {
      realEmail_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "Mobile" field.</summary>
  public const int MobileFieldNumber = 7;
  private string mobile_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Mobile {
    get { return mobile_; }
    set {
      mobile_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "PartyType" field.</summary>
  public const int PartyTypeFieldNumber = 8;
  private global::A4APartyType partyType_ = 0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::A4APartyType PartyType {
    get { return partyType_; }
    set {
      partyType_ = value;
    }
  }

  /// <summary>Field number for the "RuntimeRelation" field.</summary>
  public const int RuntimeRelationFieldNumber = 50;
  private global::A4ARelationType runtimeRelation_ = 0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::A4ARelationType RuntimeRelation {
    get { return runtimeRelation_; }
    set {
      runtimeRelation_ = value;
    }
  }

  /// <summary>Field number for the "RelatedParties" field.</summary>
  public const int RelatedPartiesFieldNumber = 100;
  private static readonly pb::FieldCodec<global::A4AParty> _repeated_relatedParties_codec
      = pb::FieldCodec.ForMessage(802, global::A4AParty.Parser);
  private readonly pbc::RepeatedField<global::A4AParty> relatedParties_ = new pbc::RepeatedField<global::A4AParty>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pbc::RepeatedField<global::A4AParty> RelatedParties {
    get { return relatedParties_; }
  }

  /// <summary>Field number for the "RelatedCategories" field.</summary>
  public const int RelatedCategoriesFieldNumber = 101;
  private static readonly pb::FieldCodec<global::A4ACategory> _repeated_relatedCategories_codec
      = pb::FieldCodec.ForMessage(810, global::A4ACategory.Parser);
  private readonly pbc::RepeatedField<global::A4ACategory> relatedCategories_ = new pbc::RepeatedField<global::A4ACategory>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pbc::RepeatedField<global::A4ACategory> RelatedCategories {
    get { return relatedCategories_; }
  }

  /// <summary>Field number for the "RelatedMessages" field.</summary>
  public const int RelatedMessagesFieldNumber = 102;
  private static readonly pb::FieldCodec<global::A4AMessage> _repeated_relatedMessages_codec
      = pb::FieldCodec.ForMessage(818, global::A4AMessage.Parser);
  private readonly pbc::RepeatedField<global::A4AMessage> relatedMessages_ = new pbc::RepeatedField<global::A4AMessage>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pbc::RepeatedField<global::A4AMessage> RelatedMessages {
    get { return relatedMessages_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as A4AParty);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(A4AParty other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Id != other.Id) return false;
    if (FirstName != other.FirstName) return false;
    if (LastName != other.LastName) return false;
    if (UserName != other.UserName) return false;
    if (AliasEmail != other.AliasEmail) return false;
    if (RealEmail != other.RealEmail) return false;
    if (Mobile != other.Mobile) return false;
    if (PartyType != other.PartyType) return false;
    if (RuntimeRelation != other.RuntimeRelation) return false;
    if(!relatedParties_.Equals(other.relatedParties_)) return false;
    if(!relatedCategories_.Equals(other.relatedCategories_)) return false;
    if(!relatedMessages_.Equals(other.relatedMessages_)) return false;
    return true;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Id.Length != 0) hash ^= Id.GetHashCode();
    if (FirstName.Length != 0) hash ^= FirstName.GetHashCode();
    if (LastName.Length != 0) hash ^= LastName.GetHashCode();
    if (UserName.Length != 0) hash ^= UserName.GetHashCode();
    if (AliasEmail.Length != 0) hash ^= AliasEmail.GetHashCode();
    if (RealEmail.Length != 0) hash ^= RealEmail.GetHashCode();
    if (Mobile.Length != 0) hash ^= Mobile.GetHashCode();
    if (PartyType != 0) hash ^= PartyType.GetHashCode();
    if (RuntimeRelation != 0) hash ^= RuntimeRelation.GetHashCode();
    hash ^= relatedParties_.GetHashCode();
    hash ^= relatedCategories_.GetHashCode();
    hash ^= relatedMessages_.GetHashCode();
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (Id.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Id);
    }
    if (FirstName.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(FirstName);
    }
    if (LastName.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(LastName);
    }
    if (UserName.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(UserName);
    }
    if (AliasEmail.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(AliasEmail);
    }
    if (RealEmail.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(RealEmail);
    }
    if (Mobile.Length != 0) {
      output.WriteRawTag(58);
      output.WriteString(Mobile);
    }
    if (PartyType != 0) {
      output.WriteRawTag(64);
      output.WriteEnum((int) PartyType);
    }
    if (RuntimeRelation != 0) {
      output.WriteRawTag(144, 3);
      output.WriteEnum((int) RuntimeRelation);
    }
    relatedParties_.WriteTo(output, _repeated_relatedParties_codec);
    relatedCategories_.WriteTo(output, _repeated_relatedCategories_codec);
    relatedMessages_.WriteTo(output, _repeated_relatedMessages_codec);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Id.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
    }
    if (FirstName.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(FirstName);
    }
    if (LastName.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(LastName);
    }
    if (UserName.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(UserName);
    }
    if (AliasEmail.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(AliasEmail);
    }
    if (RealEmail.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(RealEmail);
    }
    if (Mobile.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Mobile);
    }
    if (PartyType != 0) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) PartyType);
    }
    if (RuntimeRelation != 0) {
      size += 2 + pb::CodedOutputStream.ComputeEnumSize((int) RuntimeRelation);
    }
    size += relatedParties_.CalculateSize(_repeated_relatedParties_codec);
    size += relatedCategories_.CalculateSize(_repeated_relatedCategories_codec);
    size += relatedMessages_.CalculateSize(_repeated_relatedMessages_codec);
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(A4AParty other) {
    if (other == null) {
      return;
    }
    if (other.Id.Length != 0) {
      Id = other.Id;
    }
    if (other.FirstName.Length != 0) {
      FirstName = other.FirstName;
    }
    if (other.LastName.Length != 0) {
      LastName = other.LastName;
    }
    if (other.UserName.Length != 0) {
      UserName = other.UserName;
    }
    if (other.AliasEmail.Length != 0) {
      AliasEmail = other.AliasEmail;
    }
    if (other.RealEmail.Length != 0) {
      RealEmail = other.RealEmail;
    }
    if (other.Mobile.Length != 0) {
      Mobile = other.Mobile;
    }
    if (other.PartyType != 0) {
      PartyType = other.PartyType;
    }
    if (other.RuntimeRelation != 0) {
      RuntimeRelation = other.RuntimeRelation;
    }
    relatedParties_.Add(other.relatedParties_);
    relatedCategories_.Add(other.relatedCategories_);
    relatedMessages_.Add(other.relatedMessages_);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          input.SkipLastField();
          break;
        case 10: {
          Id = input.ReadString();
          break;
        }
        case 18: {
          FirstName = input.ReadString();
          break;
        }
        case 26: {
          LastName = input.ReadString();
          break;
        }
        case 34: {
          UserName = input.ReadString();
          break;
        }
        case 42: {
          AliasEmail = input.ReadString();
          break;
        }
        case 50: {
          RealEmail = input.ReadString();
          break;
        }
        case 58: {
          Mobile = input.ReadString();
          break;
        }
        case 64: {
          partyType_ = (global::A4APartyType) input.ReadEnum();
          break;
        }
        case 400: {
          runtimeRelation_ = (global::A4ARelationType) input.ReadEnum();
          break;
        }
        case 802: {
          relatedParties_.AddEntriesFrom(input, _repeated_relatedParties_codec);
          break;
        }
        case 810: {
          relatedCategories_.AddEntriesFrom(input, _repeated_relatedCategories_codec);
          break;
        }
        case 818: {
          relatedMessages_.AddEntriesFrom(input, _repeated_relatedMessages_codec);
          break;
        }
      }
    }
  }

}

public sealed partial class A4ACategory : pb::IMessage<A4ACategory> {
  private static readonly pb::MessageParser<A4ACategory> _parser = new pb::MessageParser<A4ACategory>(() => new A4ACategory());
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<A4ACategory> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::AppForAnswersReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public A4ACategory() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public A4ACategory(A4ACategory other) : this() {
    id_ = other.id_;
    categoryName_ = other.categoryName_;
    runtimeRelation_ = other.runtimeRelation_;
    relatedCategories_ = other.relatedCategories_.Clone();
    relatedParties_ = other.relatedParties_.Clone();
    relatedMessages_ = other.relatedMessages_.Clone();
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public A4ACategory Clone() {
    return new A4ACategory(this);
  }

  /// <summary>Field number for the "Id" field.</summary>
  public const int IdFieldNumber = 1;
  private string id_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Id {
    get { return id_; }
    set {
      id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "CategoryName" field.</summary>
  public const int CategoryNameFieldNumber = 2;
  private string categoryName_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string CategoryName {
    get { return categoryName_; }
    set {
      categoryName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "RuntimeRelation" field.</summary>
  public const int RuntimeRelationFieldNumber = 50;
  private global::A4ARelationType runtimeRelation_ = 0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::A4ARelationType RuntimeRelation {
    get { return runtimeRelation_; }
    set {
      runtimeRelation_ = value;
    }
  }

  /// <summary>Field number for the "RelatedCategories" field.</summary>
  public const int RelatedCategoriesFieldNumber = 3;
  private static readonly pb::FieldCodec<global::A4ACategory> _repeated_relatedCategories_codec
      = pb::FieldCodec.ForMessage(26, global::A4ACategory.Parser);
  private readonly pbc::RepeatedField<global::A4ACategory> relatedCategories_ = new pbc::RepeatedField<global::A4ACategory>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pbc::RepeatedField<global::A4ACategory> RelatedCategories {
    get { return relatedCategories_; }
  }

  /// <summary>Field number for the "RelatedParties" field.</summary>
  public const int RelatedPartiesFieldNumber = 4;
  private static readonly pb::FieldCodec<global::A4AParty> _repeated_relatedParties_codec
      = pb::FieldCodec.ForMessage(34, global::A4AParty.Parser);
  private readonly pbc::RepeatedField<global::A4AParty> relatedParties_ = new pbc::RepeatedField<global::A4AParty>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pbc::RepeatedField<global::A4AParty> RelatedParties {
    get { return relatedParties_; }
  }

  /// <summary>Field number for the "RelatedMessages" field.</summary>
  public const int RelatedMessagesFieldNumber = 102;
  private static readonly pb::FieldCodec<global::A4AMessage> _repeated_relatedMessages_codec
      = pb::FieldCodec.ForMessage(818, global::A4AMessage.Parser);
  private readonly pbc::RepeatedField<global::A4AMessage> relatedMessages_ = new pbc::RepeatedField<global::A4AMessage>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pbc::RepeatedField<global::A4AMessage> RelatedMessages {
    get { return relatedMessages_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as A4ACategory);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(A4ACategory other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Id != other.Id) return false;
    if (CategoryName != other.CategoryName) return false;
    if (RuntimeRelation != other.RuntimeRelation) return false;
    if(!relatedCategories_.Equals(other.relatedCategories_)) return false;
    if(!relatedParties_.Equals(other.relatedParties_)) return false;
    if(!relatedMessages_.Equals(other.relatedMessages_)) return false;
    return true;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Id.Length != 0) hash ^= Id.GetHashCode();
    if (CategoryName.Length != 0) hash ^= CategoryName.GetHashCode();
    if (RuntimeRelation != 0) hash ^= RuntimeRelation.GetHashCode();
    hash ^= relatedCategories_.GetHashCode();
    hash ^= relatedParties_.GetHashCode();
    hash ^= relatedMessages_.GetHashCode();
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (Id.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Id);
    }
    if (CategoryName.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(CategoryName);
    }
    relatedCategories_.WriteTo(output, _repeated_relatedCategories_codec);
    relatedParties_.WriteTo(output, _repeated_relatedParties_codec);
    if (RuntimeRelation != 0) {
      output.WriteRawTag(144, 3);
      output.WriteEnum((int) RuntimeRelation);
    }
    relatedMessages_.WriteTo(output, _repeated_relatedMessages_codec);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Id.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
    }
    if (CategoryName.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(CategoryName);
    }
    if (RuntimeRelation != 0) {
      size += 2 + pb::CodedOutputStream.ComputeEnumSize((int) RuntimeRelation);
    }
    size += relatedCategories_.CalculateSize(_repeated_relatedCategories_codec);
    size += relatedParties_.CalculateSize(_repeated_relatedParties_codec);
    size += relatedMessages_.CalculateSize(_repeated_relatedMessages_codec);
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(A4ACategory other) {
    if (other == null) {
      return;
    }
    if (other.Id.Length != 0) {
      Id = other.Id;
    }
    if (other.CategoryName.Length != 0) {
      CategoryName = other.CategoryName;
    }
    if (other.RuntimeRelation != 0) {
      RuntimeRelation = other.RuntimeRelation;
    }
    relatedCategories_.Add(other.relatedCategories_);
    relatedParties_.Add(other.relatedParties_);
    relatedMessages_.Add(other.relatedMessages_);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          input.SkipLastField();
          break;
        case 10: {
          Id = input.ReadString();
          break;
        }
        case 18: {
          CategoryName = input.ReadString();
          break;
        }
        case 26: {
          relatedCategories_.AddEntriesFrom(input, _repeated_relatedCategories_codec);
          break;
        }
        case 34: {
          relatedParties_.AddEntriesFrom(input, _repeated_relatedParties_codec);
          break;
        }
        case 400: {
          runtimeRelation_ = (global::A4ARelationType) input.ReadEnum();
          break;
        }
        case 818: {
          relatedMessages_.AddEntriesFrom(input, _repeated_relatedMessages_codec);
          break;
        }
      }
    }
  }

}

public sealed partial class A4AMessage : pb::IMessage<A4AMessage> {
  private static readonly pb::MessageParser<A4AMessage> _parser = new pb::MessageParser<A4AMessage>(() => new A4AMessage());
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<A4AMessage> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::AppForAnswersReflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public A4AMessage() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public A4AMessage(A4AMessage other) : this() {
    id_ = other.id_;
    content_ = other.content_;
    contentType_ = other.contentType_;
    runtimeRelation_ = other.runtimeRelation_;
    relatedParties_ = other.relatedParties_.Clone();
    relatedCategories_ = other.relatedCategories_.Clone();
    relatedMessages_ = other.relatedMessages_.Clone();
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public A4AMessage Clone() {
    return new A4AMessage(this);
  }

  /// <summary>Field number for the "Id" field.</summary>
  public const int IdFieldNumber = 1;
  private string id_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Id {
    get { return id_; }
    set {
      id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "Content" field.</summary>
  public const int ContentFieldNumber = 2;
  private string content_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Content {
    get { return content_; }
    set {
      content_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "ContentType" field.</summary>
  public const int ContentTypeFieldNumber = 3;
  private global::A4AContentType contentType_ = 0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::A4AContentType ContentType {
    get { return contentType_; }
    set {
      contentType_ = value;
    }
  }

  /// <summary>Field number for the "RuntimeRelation" field.</summary>
  public const int RuntimeRelationFieldNumber = 50;
  private global::A4ARelationType runtimeRelation_ = 0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::A4ARelationType RuntimeRelation {
    get { return runtimeRelation_; }
    set {
      runtimeRelation_ = value;
    }
  }

  /// <summary>Field number for the "RelatedParties" field.</summary>
  public const int RelatedPartiesFieldNumber = 100;
  private static readonly pb::FieldCodec<global::A4AParty> _repeated_relatedParties_codec
      = pb::FieldCodec.ForMessage(802, global::A4AParty.Parser);
  private readonly pbc::RepeatedField<global::A4AParty> relatedParties_ = new pbc::RepeatedField<global::A4AParty>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pbc::RepeatedField<global::A4AParty> RelatedParties {
    get { return relatedParties_; }
  }

  /// <summary>Field number for the "RelatedCategories" field.</summary>
  public const int RelatedCategoriesFieldNumber = 101;
  private static readonly pb::FieldCodec<global::A4ACategory> _repeated_relatedCategories_codec
      = pb::FieldCodec.ForMessage(810, global::A4ACategory.Parser);
  private readonly pbc::RepeatedField<global::A4ACategory> relatedCategories_ = new pbc::RepeatedField<global::A4ACategory>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pbc::RepeatedField<global::A4ACategory> RelatedCategories {
    get { return relatedCategories_; }
  }

  /// <summary>Field number for the "RelatedMessages" field.</summary>
  public const int RelatedMessagesFieldNumber = 102;
  private static readonly pb::FieldCodec<global::A4AMessage> _repeated_relatedMessages_codec
      = pb::FieldCodec.ForMessage(818, global::A4AMessage.Parser);
  private readonly pbc::RepeatedField<global::A4AMessage> relatedMessages_ = new pbc::RepeatedField<global::A4AMessage>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pbc::RepeatedField<global::A4AMessage> RelatedMessages {
    get { return relatedMessages_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as A4AMessage);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(A4AMessage other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Id != other.Id) return false;
    if (Content != other.Content) return false;
    if (ContentType != other.ContentType) return false;
    if (RuntimeRelation != other.RuntimeRelation) return false;
    if(!relatedParties_.Equals(other.relatedParties_)) return false;
    if(!relatedCategories_.Equals(other.relatedCategories_)) return false;
    if(!relatedMessages_.Equals(other.relatedMessages_)) return false;
    return true;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Id.Length != 0) hash ^= Id.GetHashCode();
    if (Content.Length != 0) hash ^= Content.GetHashCode();
    if (ContentType != 0) hash ^= ContentType.GetHashCode();
    if (RuntimeRelation != 0) hash ^= RuntimeRelation.GetHashCode();
    hash ^= relatedParties_.GetHashCode();
    hash ^= relatedCategories_.GetHashCode();
    hash ^= relatedMessages_.GetHashCode();
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (Id.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Id);
    }
    if (Content.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Content);
    }
    if (ContentType != 0) {
      output.WriteRawTag(24);
      output.WriteEnum((int) ContentType);
    }
    if (RuntimeRelation != 0) {
      output.WriteRawTag(144, 3);
      output.WriteEnum((int) RuntimeRelation);
    }
    relatedParties_.WriteTo(output, _repeated_relatedParties_codec);
    relatedCategories_.WriteTo(output, _repeated_relatedCategories_codec);
    relatedMessages_.WriteTo(output, _repeated_relatedMessages_codec);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Id.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
    }
    if (Content.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Content);
    }
    if (ContentType != 0) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ContentType);
    }
    if (RuntimeRelation != 0) {
      size += 2 + pb::CodedOutputStream.ComputeEnumSize((int) RuntimeRelation);
    }
    size += relatedParties_.CalculateSize(_repeated_relatedParties_codec);
    size += relatedCategories_.CalculateSize(_repeated_relatedCategories_codec);
    size += relatedMessages_.CalculateSize(_repeated_relatedMessages_codec);
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(A4AMessage other) {
    if (other == null) {
      return;
    }
    if (other.Id.Length != 0) {
      Id = other.Id;
    }
    if (other.Content.Length != 0) {
      Content = other.Content;
    }
    if (other.ContentType != 0) {
      ContentType = other.ContentType;
    }
    if (other.RuntimeRelation != 0) {
      RuntimeRelation = other.RuntimeRelation;
    }
    relatedParties_.Add(other.relatedParties_);
    relatedCategories_.Add(other.relatedCategories_);
    relatedMessages_.Add(other.relatedMessages_);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          input.SkipLastField();
          break;
        case 10: {
          Id = input.ReadString();
          break;
        }
        case 18: {
          Content = input.ReadString();
          break;
        }
        case 24: {
          contentType_ = (global::A4AContentType) input.ReadEnum();
          break;
        }
        case 400: {
          runtimeRelation_ = (global::A4ARelationType) input.ReadEnum();
          break;
        }
        case 802: {
          relatedParties_.AddEntriesFrom(input, _repeated_relatedParties_codec);
          break;
        }
        case 810: {
          relatedCategories_.AddEntriesFrom(input, _repeated_relatedCategories_codec);
          break;
        }
        case 818: {
          relatedMessages_.AddEntriesFrom(input, _repeated_relatedMessages_codec);
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
