// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FuzzyWordEntry.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from FuzzyWordEntry.proto</summary>
public static partial class FuzzyWordEntryReflection {

  #region Descriptor
  /// <summary>File descriptor for FuzzyWordEntry.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static FuzzyWordEntryReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChRGdXp6eVdvcmRFbnRyeS5wcm90byIvCg5GdXp6eVdvcmRFbnRyeRIOCgZQ",
          "aHJhc2UYASABKAkSDQoFRG9jSWQYAiABKANiBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::FuzzyWordEntry), global::FuzzyWordEntry.Parser, new[]{ "Phrase", "DocId" }, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class FuzzyWordEntry : pb::IMessage<FuzzyWordEntry> {
  private static readonly pb::MessageParser<FuzzyWordEntry> _parser = new pb::MessageParser<FuzzyWordEntry>(() => new FuzzyWordEntry());
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<FuzzyWordEntry> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::FuzzyWordEntryReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public FuzzyWordEntry() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public FuzzyWordEntry(FuzzyWordEntry other) : this() {
    phrase_ = other.phrase_;
    docId_ = other.docId_;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public FuzzyWordEntry Clone() {
    return new FuzzyWordEntry(this);
  }

  /// <summary>Field number for the "Phrase" field.</summary>
  public const int PhraseFieldNumber = 1;
  private string phrase_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Phrase {
    get { return phrase_; }
    set {
      phrase_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "DocId" field.</summary>
  public const int DocIdFieldNumber = 2;
  private long docId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public long DocId {
    get { return docId_; }
    set {
      docId_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as FuzzyWordEntry);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(FuzzyWordEntry other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Phrase != other.Phrase) return false;
    if (DocId != other.DocId) return false;
    return true;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Phrase.Length != 0) hash ^= Phrase.GetHashCode();
    if (DocId != 0L) hash ^= DocId.GetHashCode();
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (Phrase.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Phrase);
    }
    if (DocId != 0L) {
      output.WriteRawTag(16);
      output.WriteInt64(DocId);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Phrase.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Phrase);
    }
    if (DocId != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(DocId);
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(FuzzyWordEntry other) {
    if (other == null) {
      return;
    }
    if (other.Phrase.Length != 0) {
      Phrase = other.Phrase;
    }
    if (other.DocId != 0L) {
      DocId = other.DocId;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          input.SkipLastField();
          break;
        case 10: {
          Phrase = input.ReadString();
          break;
        }
        case 16: {
          DocId = input.ReadInt64();
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
